name: ApatiteControler
main: apatitecontroler.ApatiteControler
description: ApatiteServers main world control plugin
version: 2.5
commands:
   changehub:
       description: Change world
       usage: /<command>
       aliases: [hubchange,hubch,hub,world,hc,hchange,hc,changeh]
   hublist:
       description: List worlds
       usage: /<command>
   setworldspawn:
       description: setworldspawn
       usage: /<command>
   spawn:
       description: teleport to spawn
       usage: /<command>